name: GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: "18"
            cache: ${{ steps.detect-package-manager.outputs.manager }}
        - run: npm install
        - run: npm run build
        - uses: actions/upload-pages-artifact@v1
          with:
            path: dist/
        
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v1
